import { useEffect, useState } from "react";
import { createUserWithEmailAndPassword, signInWithEmailAndPassword } from "firebase/auth";
import { Link, useLocation } from "wouter";
import { ArrowRight, ArrowUpRight, CheckCircle2, Instagram, LockKeyhole, Menu, MessageCircle, Music2, ShoppingBag, Star, Truck, Twitter, UserRound, X, Youtube } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { useCart } from "@/contexts/CartContext";
import { buildWhatsAppLink } from "@shared/contact";
import { getFirebaseAuth } from "@/lib/firebase";
import { useAuth } from "@/_core/hooks/useAuth";

export type StoreProduct = { id: string; title: string; type: string; description: string; price: string; image: string; badge?: string; variantId?: string };
const navLinks = [["/", "Home"], ["/products", "Products"], ["/new-arrivals", "New Arrivals"], ["/innovation", "Innovation"], ["/support", "Support"], ["/about", "About"]] as const;

function BrandMark() { return <span className="brand-mark"><span>×</span><i /></span>; }
function goTop(close?: () => void) { close?.(); requestAnimationFrame(() => window.scrollTo({ top: 0, behavior: "smooth" })); }

export function PremiumNavbar({ openCart }: { openCart: () => void }) { const [mobile, setMobile] = useState(false); const [location] = useLocation(); const { itemCount } = useCart(); return <><header className="navbar premium-navbar"><Link href="/" className="brand"><BrandMark /><span>Liverton</span></Link><nav className="premium-nav-links" aria-label="Primary navigation">{navLinks.map(([href, label]) => <Link key={href} href={href} className={location === href || (href !== "/" && location.startsWith(href)) ? "nav-link active" : "nav-link"} onClick={() => goTop()}>{label}</Link>)}</nav><div className="nav-actions"><Link href="/account" className="account-link"><UserRound size={17} /><span>Account</span></Link><button className="nav-icon cart-button" onClick={openCart} aria-label="Open cart"><ShoppingBag size={18} /><span>{itemCount}</span></button><button className="menu-button" onClick={() => setMobile(true)} aria-label="Open menu"><Menu size={21} /></button></div></header><Sheet open={mobile} onOpenChange={setMobile}><SheetContent side="right" className="premium-mobile-sheet"><SheetHeader><SheetTitle><span className="sheet-brand"><BrandMark /> Liverton</span></SheetTitle></SheetHeader><nav className="mobile-nav" aria-label="Mobile navigation">{navLinks.map(([href, label]) => <Link key={href} href={href} onClick={() => goTop(() => setMobile(false))}>{label}<ArrowRight size={16} /></Link>)}</nav><Link href="/account" className="mobile-account" onClick={() => setMobile(false)}><UserRound size={18} /> Sign in or create account</Link><button className="mobile-cart" onClick={() => { setMobile(false); openCart(); }}><ShoppingBag size={18} /> Cart <span>{itemCount}</span></button></SheetContent></Sheet></>; }

export function PremiumFooter() { const [email, setEmail] = useState(""); const [joined, setJoined] = useState(false); const socials = [{ href: "https://instagram.com/smartify_finds", label: "Instagram", icon: "instagram", color: "#E4405F" }, { href: "https://www.tiktok.com/@smartify_finds", label: "TikTok", icon: "tiktok", color: "#25F4EE" }, { href: "https://youtube.com/@smartify_finds", label: "YouTube", icon: "youtube", color: "#FF0000" }, { href: "https://x.com/smartify_finds", label: "X", icon: "x", color: "#FFFFFF" }, { href: "https://wa.me/256705954597", label: "WhatsApp", icon: "whatsapp", color: "#25D366" }]; return <footer className="footer premium-footer"><div className="footer-grid"><div className="footer-brand"><Link href="/" className="brand brand-light"><BrandMark /> Liverton</Link><p>Technology that makes more room for living. Thoughtful devices, clear design, and support that stays human.</p><div className="socials premium-socials">{socials.map(({ href, label, icon, color }) => <a href={href} target="_blank" rel="noreferrer" aria-label={label} key={label} className={`social-brand social-${icon}`}><img src={`https://cdn.simpleicons.org/${icon}/${color.replace("#", "")}`} alt="" aria-hidden="true" /></a>)}</div><div className="sponsored-by"><span>Sponsored by</span><strong>Liverton</strong></div></div><div className="footer-links"><div><h4>Explore</h4><Link href="/products">Products</Link><Link href="/new-arrivals">New Arrivals</Link><Link href="/innovation">Innovation</Link><Link href="/solutions">Solutions</Link></div><div><h4>Company</h4><Link href="/about">About Us</Link><Link href="/support">Support</Link><Link href="/account">Account</Link></div><div><h4>Help</h4><Link href="/contact">Contact</Link><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms of Service</Link></div></div><div className="footer-newsletter"><span className="eyebrow muted">THE LIVERTON SIGNAL</span><h3>New arrivals, considered.</h3><p>Product drops, care notes, and occasional inspiration.</p>{joined ? <div className="joined">You’re on the list.</div> : <form onSubmit={e => { e.preventDefault(); setJoined(email.includes("@")); }}><Input type="email" placeholder="Your email address" value={email} onChange={e => setEmail(e.target.value)} required /><Button type="submit">Join <ArrowRight size={15} /></Button></form>}</div></div><div className="footer-bottom"><span>© 2026 Liverton Stores</span><span>Sponsored by Liverton · Designed with care.</span></div></footer>; }

export function ProductDetail({ product, onAdd }: { product: StoreProduct; onAdd: (product: StoreProduct) => void }) { return <main className="product-detail-page"><div className="detail-breadcrumb"><Link href="/products">Products</Link><ArrowRight size={14} />{product.title}</div><section className="product-detail"><div className="detail-image"><img src={product.image} alt={product.title} /></div><div className="detail-copy"><span className="eyebrow">{product.type} · Liverton Stores</span><h1>{product.title}</h1><div className="detail-rating"><span className="review-stars">★★★★★</span> 4.8 <span>128 reviews</span></div><p className="detail-description">{product.description} Designed for the way you live, with considered materials, dependable performance, and a calm experience from first setup to everyday use.</p><div className="detail-price">${product.price}<small>USD · taxes calculated at checkout</small></div><div className="detail-actions"><button className="cta-button" onClick={() => onAdd(product)}>Add to cart <ShoppingBag size={16} /></button><Link href="/checkout" className="quiet-link">Buy now <ArrowUpRight size={16} /></Link></div><div className="detail-perks"><span><Truck size={17} /> Fast delivery</span><span><LockKeyhole size={17} /> Secure checkout</span></div></div></section><section className="reviews-block"><div className="section-top"><div><span className="eyebrow">Loved by the Liverton community</span><h2>Reviews for {product.title}</h2></div><strong className="rating-summary">4.8 <span>★★★★★</span><small>128 verified reviews</small></strong></div><div className="review-grid">{[["Amina K.", "The details feel considered and the setup was effortless."], ["Daniel M.", "Premium without the fuss. It has become part of my daily rhythm."], ["Sarah N.", "Beautiful design, fast delivery, and genuinely helpful support."]].map(([name, review]) => <article className="review-card" key={name}><div className="review-stars">★★★★★</div><p>“{review}”</p><strong>{name}</strong><small><CheckCircle2 size={13} /> Verified purchase</small></article>)}</div></section></main>; }

export function CheckoutPage() { const { cart, itemCount, proceedToCheckout } = useCart(); return <main className="checkout-page"><div className="checkout-heading"><span className="eyebrow">Liverton Stores checkout</span><h1>Ready when <span>you are.</span></h1><p>Review your collection, then continue to our secure payment partner.</p></div>{cart?.items?.length ? <div className="checkout-layout"><section className="checkout-card"><h2>Your collection <Badge>{itemCount} items</Badge></h2>{cart.items.map(item => <div className="checkout-item" key={item.lineId}><img src={item.image?.url} alt={item.productTitle} /><div><strong>{item.productTitle}</strong><span>Qty {item.quantity}</span></div><b>{item.unitPrice.amount} {item.unitPrice.currencyCode}</b></div>)}</section><aside className="checkout-summary"><span>Subtotal</span><strong>{cart.subtotal.amount} {cart.subtotal.currencyCode}</strong><p>Shipping and taxes are calculated securely at checkout.</p><Button onClick={proceedToCheckout}>Continue to secure checkout <ArrowUpRight size={16} /></Button></aside></div> : <div className="empty-cart checkout-empty"><ShoppingBag size={34} /><h2>Your cart is waiting.</h2><p>Add something considered to continue.</p><Link href="/products" className="cta-button">Browse products <ArrowRight size={15} /></Link></div>}</main>; }

export function LoginPrompt() { const { isAuthenticated } = useAuth(); const [open, setOpen] = useState(false); const [mode, setMode] = useState<"login" | "create">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); useEffect(() => { if (!isAuthenticated && !localStorage.getItem("liverton-login-dismissed")) { const timer = window.setTimeout(() => setOpen(true), 4200); return () => window.clearTimeout(timer); } }, [isAuthenticated]); if (isAuthenticated || !open) return null; async function submit(e: React.FormEvent) { e.preventDefault(); setError(""); const auth = getFirebaseAuth(); if (!auth) { setError("Sign-in is being configured. You can continue as a guest."); return; } try { if (mode === "login") await signInWithEmailAndPassword(auth, email, password); else await createUserWithEmailAndPassword(auth, email, password); setOpen(false); } catch (err) { setError(err instanceof Error ? err.message.replace("Firebase: ", "") : "Please check your details."); } } return <div className="login-overlay" role="dialog" aria-modal="true" aria-labelledby="login-title"><div className="login-card"><button className="login-close" onClick={() => { setOpen(false); localStorage.setItem("liverton-login-dismissed", "1"); }} aria-label="Dismiss login prompt"><X size={18} /></button><div className="login-mark"><BrandMark /></div><span className="eyebrow">Liverton Stores account</span><h2 id="login-title">Keep your favourites <span>close.</span></h2><p>Sign in for faster checkout and a more personal store experience. You can also continue as a guest.</p><div className="login-tabs"><button className={mode === "login" ? "active" : ""} onClick={() => setMode("login")}>Sign in</button><button className={mode === "create" ? "active" : ""} onClick={() => setMode("create")}>Create account</button></div><form onSubmit={submit}><Input type="email" placeholder="Email address" value={email} onChange={e => setEmail(e.target.value)} required /><Input type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} minLength={6} required /><Button type="submit">{mode === "login" ? "Sign in" : "Create account"} <ArrowRight size={15} /></Button></form>{error && <small className="login-error">{error}</small>}<button className="guest-button" onClick={() => { setOpen(false); localStorage.setItem("liverton-login-dismissed", "1"); }}>Continue as guest</button></div></div>; }
